### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kyojitsu** [RainbowMage/OverlayPlugin#10]
2/22/2015 11:24:02 AM: Error: MiniParseOverlay: Update: System.MissingMethodException: Method not found: 'Xilium.CefGlue.CefBrowser RainbowMage.HtmlRenderer.Renderer.get_Browser()'.
   at RainbowMage.OverlayPlugin.MiniParseOverlay.Update()
   at RainbowMage.OverlayPlugin.OverlayBase`1.<InitializeTimer>b__6(Object o, ElapsedEventArgs e) in c:\Users\John\Documents\GitHub\OverlayPlugin\OverlayPlugin\OverlayBase.cs:line 166

???

**Comment by RainbowMage** [comment]
The error message says HtmlRenderer.dll is missing or corrupted.

Please reinstall plugin using `full` archive.
