### ISSUE TITLE
Plugin Initialization Failed

### ISSUE THREAD

**Issue by IrealiTY** [RainbowMage/OverlayPlugin#25]
Adding the Plugin works.
Enabling doesn't.

![image](https://cloud.githubusercontent.com/assets/1223686/6986183/1ae5c318-da3b-11e4-8870-d69e8553055f.png)

Other Plugins work ok.
Old versions of the overlay also worked. But suddenly also stopped

````
***** 2015-04-03T19:51:18 - Enabling plugin: D:\Advanced Combat Tracker\OverlayPlugin-0.3.3.5-x64-full\OverlayPlugin.dll
***** 2015-04-03T19:51:18 - Plugin Initialization Failed
System.ArgumentNullException: Array cannot be null.
   at RainbowMage.OverlayPlugin.PluginLoader.Initialize(TabPage pluginScreenSpace, Label pluginStatusText)
   at Advanced_Combat_Tracker.FormActMain.pluginPanelEnabledChecked(Object sender, EventArgs e)
   at Advanced_Combat_Tracker.FormActMain.WriteExceptionLog(Exception ex, String MoreInfo)
   at Advanced_Combat_Tracker.FormActMain.pluginPanelEnabledChecked(Object sender, EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Advanced_Combat_Tracker.ActLoader.Main(String[] args)
*****
````

Edit: i tried version 0.3.3.5 but it's the same with 0.3.3.6

**Comment by RainbowMage** [comment]
Please try:

* Remove OverlayPlugin.dll from your ACT plugin list.
* Remove other plugins except FFXIV_ACT_Plugin.dll.
* Shutdown ACT.
* Delete old plugin files. (including `OverlayPlugin.Core.dll`, `OverlayPlugin.Common.dll`, etc.)
* Delete configuration file located at `%appdada%\Advanced Combat Tracker\Config\RainbowMage.OverlayPlugin.xml` if exists.
* Download latest `full` archive of plugin, unblock and extract it.
* Launch ACT and add latest OverlayPlugin.dll.
* Try if it works.

**Comment by IrealiTY** [comment]
It didnt work by deleting old plugin files.
I had to delete all ACT files in AppData, then it worked :)

Thanks for helping!
