### ISSUE TITLE
System.ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by mlvnk** [RainbowMage/OverlayPlugin#33]
Hi, i got below error when trying to use rainbow mage plug in. This is my first time using this plugin.

System.ArgumentNummException: Value cannot be null.
Parameter name: source
  at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable1 source, Func 2 predicate)
 at RainbowMage.OverlayPlugin.PluginMain.InitializeOverlays()
 at RainbowMage.OverlayPlugin.PluginMain.InitPlugin(TabPage pluginScreenSpace, Label pluginStatusText)

Can you please advise what went wrong? Thanks.

**Comment by mlvnk** [comment]
I forgot to mention this is the file name i downloaded;
OverlayPlugin-0.3.3.8-x64-full.zip

**Comment by RainbowMage** [comment]
Cleaning up old issues.

Please repost if you have not resolve the issues yet.
