### ISSUE TITLE
Another System.NullReferenceException

### ISSUE THREAD

**Issue by tiliv** [RainbowMage/OverlayPlugin#42]
I seem to be having the same trouble as the user in issue #22

When the plugin loads, there are no errors, but the overlay is not visible.  Unloading/reloading the overlay makes the error appear.  I followed the instructions to remove/clean the plugin installation (removing the `%appdata%` xml config, etc) and but the issue still remains.

Running latest Windows 10, and I have .NET 4.6 installed.

Thanks for any help you can provide.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at RainbowMage.OverlayPlugin.Overlays.MiniParseOverlay.Navigate(String url)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1063.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Advanced Combat Tracker
    Assembly Version: 3.2.2.252
    Win32 Version: 3.2.2.252
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/ACTx86.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
GammaJul.LgLcd
    Assembly Version: 1.1.3.0
    Win32 Version: 1.1.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/GammaJul.LgLcd.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 0.85.5.452
    Win32 Version: 0.85.5.452
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/ICSharpCode.SharpZipLib.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
FFXIV_ACT_Plugin
    Assembly Version: 1.4.2.9
    Win32 Version: 3.2.2.252
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/ACTx86.exe
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
OverlayPlugin
    Assembly Version: 0.3.3.9
    Win32 Version: 3.2.2.252
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/ACTx86.exe
----------------------------------------
OverlayPlugin.Common
    Assembly Version: 0.3.3.9
    Win32 Version: 0.3.3.9
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/rainbowmage/OverlayPlugin-0.3.3.9-x86-full/OverlayPlugin.Common.dll
----------------------------------------
OverlayPlugin.Core
    Assembly Version: 0.3.3.9
    Win32 Version: 0.3.3.9
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/rainbowmage/OverlayPlugin-0.3.3.9-x86-full/OverlayPlugin.Core.dll
----------------------------------------
HtmlRenderer
    Assembly Version: 1.0.1.4
    Win32 Version: 1.0.1.4
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/rainbowmage/OverlayPlugin-0.3.3.9-x86-full/HtmlRenderer.dll
----------------------------------------
Xilium.CefGlue
    Assembly Version: 3.2272.2035.0
    Win32 Version: 3.2272.2035.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/rainbowmage/OverlayPlugin-0.3.3.9-x86-full/Xilium.CefGlue.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by lucky48158** [comment]
You're lucky you can even get the plugin to initialize on Windows 10.  I can't.  I get this error whenever I try.  Everything is unblocked so that isn't the issue.

![screenshot 21](https://cloud.githubusercontent.com/assets/17618967/13498666/e7a3b776-e128-11e5-849c-a631c51c6ce0.png)

**Comment by lucky48158** [comment]
I got it!  Try running ACT as administrator and then enable the plugin.  No errors this time.

**Comment by tiliv** [comment]
Hm, I will try it again, but I do have administrator mode marked in the compatibility settings.  Something's up, I just can't figure out what's different in this install compared to previous ones.  I'll have to post an update later, probably tonight.

**Comment by neptuwunium** [comment]
Make sure the bitsize of the plugin is the same as your system/installation. Running the x86 plugin on a x64 system or installation will cause the thing to fail (at least on my end)

In other words, try the x64 bit version if you're running the x86 bit Overlay plugin, and vice versa.
