### ISSUE TITLE
.NET issue when enabling

### ISSUE THREAD

**Issue by iammoney45** [RainbowMage/OverlayPlugin#43]
I have used this program with no issues in the past, but now after reinstalling  ACT and having to re-enable my overlay, I can not enable Rainbowmage. Here is a screenshot. 
https://gyazo.com/951e63d1b18ec53899e075b21571ae20

**Comment by pkminer30** [comment]
Edit Advanced Combat Tracker.exe.config (both configs) and add the following line after <runtime> (after line 3)

```
<loadFromRemoteSources  enabled=”true” />
```

**Comment by iammoney45** [comment]
I made the change and i was able to enable it, but now when i go and try to change any of the settings i get this error: 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at RainbowMage.OverlayPlugin.OverlayBase`1.<InitializeConfigHandlers>b__e(Object o, VisibleStateChangedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at RainbowMage.OverlayPlugin.OverlayConfigBase.set_IsVisible(Boolean value)
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE

##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

Advanced Combat Tracker
    Assembly Version: 3.3.0.254
    Win32 Version: 3.3.0.254

##     CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1075.0 built by: NETFXREL3STAGE

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

GammaJul.LgLcd
    Assembly Version: 1.1.3.0
    Win32 Version: 1.1.3.0

##     CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/GammaJul.LgLcd.DLL

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

ICSharpCode.SharpZipLib
    Assembly Version: 0.85.5.452
    Win32 Version: 0.85.5.452

##     CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/ICSharpCode.SharpZipLib.DLL

System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

FFXIV_ACT_Plugin
    Assembly Version: 1.4.2.14
    Win32 Version: 3.3.0.254

##     CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe

System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

OverlayPlugin
    Assembly Version: 0.3.3.8
    Win32 Version: 3.3.0.254

##     CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/Advanced%20Combat%20Tracker.exe

OverlayPlugin.Common
    Assembly Version: 0.3.3.8
    Win32 Version: 0.3.3.8

##     CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin-0.3.3.8-x86-full/OverlayPlugin.Common.dll

OverlayPlugin.Core
    Assembly Version: 0.3.3.8
    Win32 Version: 0.3.3.8

##     CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin-0.3.3.8-x86-full/OverlayPlugin.Core.dll

HtmlRenderer
    Assembly Version: 1.0.1.4
    Win32 Version: 1.0.1.4

##     CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin-0.3.3.8-x86-full/HtmlRenderer.dll

Xilium.CefGlue
    Assembly Version: 3.2171.1949.0
    Win32 Version: 3.2171.1949.0

##     CodeBase: file:///C:/Program%20Files%20(x86)/Advanced%20Combat%20Tracker/OverlayPlugin-0.3.3.8-x86-full/Xilium.CefGlue.dll

System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2

##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by pkminer30** [comment]
run it administrator with that fix?

**Comment by pkminer30** [comment]
also use the 0.3.3.9 version
https://github.com/RainbowMage/OverlayPlugin/releases/download/0.3.3.9/OverlayPlugin-0.3.3.9-x64-full.zip

**Comment by iammoney45** [comment]
Using the new version fixed it. I was using the one I had previously downloaded, but i guess sn update to something broke it. Thank you for the help.

**Comment by pkminer30** [comment]
No problem. 0.3.3.8 broke for me during the windows 10 update that was forced at the beginning of march where it puts you on .net framework 4.6 whereas 0.3.3.8 = 4.5.1 so it could be due to this. But ye i had to reset mine earlier today. you might need to reinstall act from scratch every now and again so remember to write down the fix ok bud :D.
