### ISSUE TITLE
Rainbowmage Overlay Loading error

### ISSUE THREAD

**Issue by Nodochi88** [RainbowMage/OverlayPlugin#53]
3/24/2017 12:58:22 AM: Info: InitPlugin: PluginDirectory = C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin-0.3.3.9-x86-full
3/24/2017 12:58:22 AM: Warning: LoadConfig: System.IO.FileNotFoundException: Specified file is not exists.
File name: 'C:\Users\StewartGaming\AppData\Roaming\Advanced Combat Tracker\Config\RainbowMage.OverlayPlugin.config.xml'
   at RainbowMage.OverlayPlugin.PluginConfig.LoadXml(String pluginDirectory, String path)
   at RainbowMage.OverlayPlugin.PluginMain.LoadConfig()
3/24/2017 12:58:22 AM: Info: LoadConfig: Creating new configuration.
3/24/2017 12:58:22 AM: Info: InitPlugin: Initialized.
3/24/2017 12:59:20 AM: Error: Mini Parse: XivWindowWatcher: System.NullReferenceException: Object reference not set to an instance of an object.
   at RainbowMage.OverlayPlugin.OverlayBase`1.<InitializeTimer>b__b(Object o, ElapsedEventArgs e)
3/24/2017 12:59:20 AM: Error: Spell Timer: XivWindowWatcher: System.NullReferenceException: Object reference not set to an instance of an object.
   at RainbowMage.OverlayPlugin.OverlayBase`1.<InitializeTimer>b__b(Object o, ElapsedEventArgs e)

Everytime I try to load in the .dll into the ACT, I get this. Everytime. It keeps telling me that a file doesn't exist, which is true. But I can't find anything in any type of support forum for that file not existing, just to delete it if it's corrupted. I've done this before many times for a lot of people, and when this started happening I went and followed like 4 different guides to try to figure out if maybe I just did something wrong. No matter what I do, I can't do anything but get this error.

I'm using the x86 version, if I try to run the x64 version it just auto-crashes, doesn't even give me time to get errors.

**Comment by hibiyasleep** [comment]
You need to execute ACT as administrator permission, since windows focus detection needs permission.

**Comment by Nodochi88** [comment]
Hello, thanks for the response. Unfortunately I already am running it in admin. The error persists regardless of how act is opened
