### ISSUE TITLE
"Reload Overlay" error

### ISSUE THREAD

**Issue by MIS4KI** [RainbowMage/OverlayPlugin#61]
For some reason I'm not finding an accurate answer to this.

I managed to set up ACT and everything works fine, except when I want to pick a URL in the OverlayPlugin window I get an error message:

https://gyazo.com/10638d46fa0cf0f3c94623634b1285aa

(An exception not handled has occurred in your application program. If you click continue, this error will be ignored. If you click End, the application is immediately terminated.")

Someone can help me through this please? I even uninstalled everything and this doesn't solve it.

**Comment by viseriod** [comment]
I'm having the same issue. The plugin isn't managing this file at all. I have no idea why. But it won't even create a new one after deleting it.

10/9/2018 11:58:06 AM: Warning: LoadConfig: System.IO.FileNotFoundException: Specified file is not exists.
File name: 'C:\Users\gleas\AppData\Roaming\Advanced Combat Tracker\Config\RainbowMage.OverlayPlugin.config.xml'
   at RainbowMage.OverlayPlugin.PluginConfig.LoadXml(String pluginDirectory, String path)
   at RainbowMage.OverlayPlugin.PluginMain.LoadConfig()
