### ISSUE TITLE
Exception occurring when executing CefRuntime.Load();

### ISSUE THREAD

**Issue by ad0ran** [RainbowMage/OverlayPlugin#8]
I'm on Windows 8 x64 Pro N

An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

   at Xilium.CefGlue.Interop.libcef.api_hash(Int32 entry)
   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash()
   at Xilium.CefGlue.CefRuntime.CheckVersion()
   at Xilium.CefGlue.CefRuntime.Load(String path)
   at Xilium.CefGlue.CefRuntime.Load()
   at RainbowMage.HtmlRenderer.Renderer.Initialize() in d:\Advanced Combat Tracker\Plugins\OverlayPlugin-master\HtmlRenderer\Renderer.cs:line 129
   at RainbowMage.OverlayPlugin.OverlayForm..ctor(String url, Int32 maxFrameRate) in d:\Advanced Combat Tracker\Plugins\OverlayPlugin-master\OverlayPlugin\OverlayForm.cs:line 62
   at RainbowMage.OverlayPlugin.OverlayBase`1.InitializeOverlay() in d:\Advanced Combat Tracker\Plugins\OverlayPlugin-master\OverlayPlugin\OverlayBase.cs:line 48

**Comment by BMCSamael** [comment]
Make sure you unblock it by right click properties unblock

**Comment by ad0ran** [comment]
@BMCSamael that wasn't the issue. It was actually due to the fact that I was running ACT in x64bit. Running it on x86 mode solved the issue.
